## Семинар 1

# Тема: Повторение библиотек numpy, pandas, matplotlib, seaborn.

Импортируем необходимые библиотеки:

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Задания для выполнения:

## 1. Создайте двумерный numpy-массив (матрицу), элементами которой являются числа из таблицы умножения. Выделите из этой матрицы новую матрицу, состоящую из первых трёх столбцов данной.

In [2]:
a = np.arange(1, 11).reshape(10,1) * np.arange(1, 11)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [3]:
a[:, :3]

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18],
       [ 7, 14, 21],
       [ 8, 16, 24],
       [ 9, 18, 27],
       [10, 20, 30]])

## 2. Создайте функцию, которая возвращает диагональную матрицу, по диагонали которой располагаются члены арифметической прогрессии. Пусть эта функция принимает три значения: размер матрицы, первый элемент и разность арифметической прогрессии. Выведите матрицу с конкретными значениями параметров. Напечатайте эту матрицу, используя print.

In [4]:
def matrix(size, first, diff):
    diag_el = [first + i*diff for i in range(size)]
    diag_matrix = np.diag(diag_el)
    return diag_matrix
matrix(5, 1, 3)

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  7,  0,  0],
       [ 0,  0,  0, 10,  0],
       [ 0,  0,  0,  0, 13]])

In [5]:
A = matrix(5, 1, 3)
print(A)

[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  7  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 13]]


## 3. Создайте одномерный numpy-массив, содержащий числа от 1 до 25. Превратите его в матрицу размета $5 \times 5$. Выделите из этой матрицы второй столбец в виде столбца (двумерный numpy-массив) и в виде строки (одномерный numpy-массив).

In [6]:
arr = np.arange(1, 26)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [7]:
A = arr.reshape(5, 5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
A[:, 1:2]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [9]:
A[:, 1]

array([ 2,  7, 12, 17, 22])

## 4. Создайте функцию, которая возвращает квадратную матрицу, содержащую единицы на границе и нули внутри. Пусть эта функция принимает размер матрицы.

In [10]:
def quadrat(size):
    a = np.zeros(size)
    a[:, 0] = 1
    a[0, :] = 1
    a[:, -1] = 1
    a[-1, :] = 1
    return a

quadrat([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## 5. Создайте две матрицы размером 5 $\times$ 5. Первая матрица должна содержать цифру 5 в шахматном порядке, остальные значения - нули. Вторая матрица - треугольная, состоящая из цифры 5 на местах с ненулевыми значениями. Посчитайте их детерминанты и найдите обратные матрицы (если это возможно).

In [11]:
matrix1 = np.zeros((5, 5))
matrix1[0::2, 0::2] = 5
matrix1[1::2, 1::2] = 5
matrix1

array([[5., 0., 5., 0., 5.],
       [0., 5., 0., 5., 0.],
       [5., 0., 5., 0., 5.],
       [0., 5., 0., 5., 0.],
       [5., 0., 5., 0., 5.]])

In [12]:
matrix2 = np.zeros((5, 5))
for i in range(5):
    for j in range(i+1):
        matrix2[j, i] = 5
matrix2

array([[5., 5., 5., 5., 5.],
       [0., 5., 5., 5., 5.],
       [0., 0., 5., 5., 5.],
       [0., 0., 0., 5., 5.],
       [0., 0., 0., 0., 5.]])

In [13]:
np.linalg.det(matrix1)

0.0

In [14]:
np.linalg.det(matrix2)

3124.999999999999

In [15]:
try:
    inv_matrix1 = np.linalg.inv(matrix1)
    print(f'Обратная матрица {inv_matrix1}')
except:
    print(f'Обратной матрицы не существует')

Обратной матрицы не существует


In [16]:
try:
    inv_matrix2 = np.linalg.inv(matrix2)
    print(f'Обратная матрица {inv_matrix2}')
except:
    print(f'Обратной матрицы не существует')

Обратная матрица [[ 0.2 -0.2  0.   0.   0. ]
 [ 0.   0.2 -0.2  0.   0. ]
 [ 0.   0.   0.2 -0.2  0. ]
 [ 0.   0.   0.   0.2 -0.2]
 [ 0.   0.   0.   0.   0.2]]


## 6. С помощью pandas загрузите датасет для предсказания цены квартиры, прилагающийся к этой работе. Создайте его копию. Выведите на экран 7 первых, 7 последних и 7 случайных строк данных.

In [17]:
data = pd.read_csv('data.csv')
data

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0     11809          27    3.0  115.027311         NaN           10.0      4   
1      3013          22    1.0   39.832524   23.169223            8.0      7   
2      8215           1    3.0   78.342215   47.671972           10.0      2   
3      2352           1    1.0   40.409907         NaN            1.0     10   
4     13866          94    2.0   64.285067   38.562517            9.0     16   
...     ...         ...    ...         ...         ...            ...    ...   
9995   1260          61    2.0   49.090728   33.272626            6.0      3   
9996  16265          27    2.0   64.307684   37.038420            9.0     13   
9997   2795         178    1.0   29.648057   16.555363            5.0      3   
9998  14561          21    1.0   32.330292   22.326870            5.0      3   
9999   7202          94    1.0   35.815476   22.301367            6.0      9   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
0           10.0       2014   0.075424         B         B        11   
1            8.0       1966   0.118537         B         B        30   
2           17.0       1988   0.025609         B         B        33   
3           22.0       1977   0.007122         B         B         1   
4           16.0       1972   0.282798         B         B        33   
...          ...        ...        ...       ...       ...       ...   
9995        12.0       1981   0.300323         B         B        52   
9996         0.0       1977   0.072158         B         B         2   
9997         5.0       1958   0.460556         B         B        20   
9998         9.0       1969   0.194489         B         B        47   
9999         9.0       1975   0.127376         B         B        43   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
0         3097         0           NaN            0        0       B   
1         6207         1        1183.0            1        0       B   
2         5261         0         240.0            3        1       B   
3          264         0           NaN            0        1       B   
4         8667         2           NaN            0        6       B   
...        ...       ...           ...          ...      ...     ...   
9995     10311         6           NaN            1        9       B   
9996       629         1           NaN            0        0       A   
9997      4386        14           NaN            1        5       B   
9998      8004         3         125.0            3        5       B   
9999      8429         3           NaN            3        9       B   

              Price  
0     305018.871089  
1     177734.553407  
2     282078.720850  
3     168106.007630  
4     343995.102962  
...             ...  
9995  119367.455796  
9996  199715.148807  
9997  165953.912580  
9998  171842.411855  
9999  177685.627486  

[10000 rows x 20 columns]

In [18]:
data.head(7)

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0  11809          27    3.0  115.027311         NaN           10.0      4   
1   3013          22    1.0   39.832524   23.169223            8.0      7   
2   8215           1    3.0   78.342215   47.671972           10.0      2   
3   2352           1    1.0   40.409907         NaN            1.0     10   
4  13866          94    2.0   64.285067   38.562517            9.0     16   
5   5804          99    3.0   62.528465   47.103833            6.0      9   
6   8864          44    1.0   33.938750   21.772930            9.0      1   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0        10.0       2014   0.075424         B         B        11      3097   
1         8.0       1966   0.118537         B         B        30      6207   
2        17.0       1988   0.025609         B         B        33      5261   
3        22.0       1977   0.007122         B         B         1       264   
4        16.0       1972   0.282798         B         B        33      8667   
5         9.0       1972   0.012339         B         B        35      5776   
6        12.0       1968   0.232205         B         B        24      4860   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
0         0           NaN            0        0       B  305018.871089  
1         1        1183.0            1        0       B  177734.553407  
2         0         240.0            3        1       B  282078.720850  
3         0           NaN            0        1       B  168106.007630  
4         2           NaN            0        6       B  343995.102962  
5         1        2078.0            2        4       B  161044.944138  
6         1          80.0            0        3       B  142402.739272

In [19]:
data.tail(7)

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
9993   9289           1    3.0  84.486078   88.931509            0.0      4   
9994   4356           9    1.0  43.303458   21.519087            8.0     12   
9995   1260          61    2.0  49.090728   33.272626            6.0      3   
9996  16265          27    2.0  64.307684   37.038420            9.0     13   
9997   2795         178    1.0  29.648057   16.555363            5.0      3   
9998  14561          21    1.0  32.330292   22.326870            5.0      3   
9999   7202          94    1.0  35.815476   22.301367            6.0      9   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
9993        22.0       2016   0.007122         B         B         1   
9994        14.0       1992   0.161532         B         B        25   
9995        12.0       1981   0.300323         B         B        52   
9996         0.0       1977   0.072158         B         B         2   
9997         5.0       1958   0.460556         B         B        20   
9998         9.0       1969   0.194489         B         B        47   
9999         9.0       1975   0.127376         B         B        43   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
9993       264         0           NaN            0        1       B   
9994      5648         1          30.0            2        4       B   
9995     10311         6           NaN            1        9       B   
9996       629         1           NaN            0        0       A   
9997      4386        14           NaN            1        5       B   
9998      8004         3         125.0            3        5       B   
9999      8429         3           NaN            3        9       B   

              Price  
9993  264213.558631  
9994  136744.340827  
9995  119367.455796  
9996  199715.148807  
9997  165953.912580  
9998  171842.411855  
9999  177685.627486

In [20]:
data.sample(7)

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
2706  13158         104    2.0   81.634818   45.236328            9.0      6   
1929  14621          59    2.0   73.431719         NaN            1.0     25   
1203  13129          73    1.0   46.765168   48.240133            1.0      6   
4147  16416          23    3.0   65.568252   64.165779           11.0     11   
6450   2603          30    3.0  162.587886  164.526757            0.0      2   
8174   6535          47    2.0   56.798431   33.557656            8.0     18   
1777    365          22    3.0   79.812327   47.296211           12.0      4   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
2706         9.0       1955   0.000078         B         B        22   
1929        25.0       1977   0.019509         B         B        37   
1203         9.0       2016   0.042032         B         B        37   
4147        12.0       2018   0.034656         B         B         0   
6450         3.0       1977   0.000078         B         B        22   
8174        16.0       1982   0.101872         B         B        23   
1777        12.0       1998   0.118537         B         B        30   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
2706      6398       141        1046.0            3       23       B   
1929      7687        11         176.0            5        5       B   
1203      6856        84        1940.0            2        5       B   
4147       168         0           NaN            0        0       B   
6450      6398       141        1046.0            3       23       B   
8174      4583         3           NaN            3        3       B   
1777      6207         1        1183.0            1        0       B   

              Price  
2706  418817.402538  
1929  366701.098697  
1203  404790.563784  
4147  134710.019123  
6450  207407.352593  
8174  266994.283576  
1777  354706.677057

## 7. Выведите информацию о данных. Выведите количество строк, количество столбцов, тип данных каждого признака.

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             10000 non-null  int64  
 1   DistrictId     10000 non-null  int64  
 2   Rooms          10000 non-null  float64
 3   Square         10000 non-null  float64
 4   LifeSquare     7887 non-null   float64
 5   KitchenSquare  10000 non-null  float64
 6   Floor          10000 non-null  int64  
 7   HouseFloor     10000 non-null  float64
 8   HouseYear      10000 non-null  int64  
 9   Ecology_1      10000 non-null  float64
 10  Ecology_2      10000 non-null  object 
 11  Ecology_3      10000 non-null  object 
 12  Social_1       10000 non-null  int64  
 13  Social_2       10000 non-null  int64  
 14  Social_3       10000 non-null  int64  
 15  Healthcare_1   5202 non-null   float64
 16  Helthcare_2    10000 non-null  int64  
 17  Shops_1        10000 non-null  int64  
 18  Shops_2

In [22]:
data.shape[0]

10000

In [23]:
data.shape[1]

20

In [24]:
data.dtypes

Id                 int64
DistrictId         int64
Rooms            float64
Square           float64
LifeSquare       float64
KitchenSquare    float64
Floor              int64
HouseFloor       float64
HouseYear          int64
Ecology_1        float64
Ecology_2         object
Ecology_3         object
Social_1           int64
Social_2           int64
Social_3           int64
Healthcare_1     float64
Helthcare_2        int64
Shops_1            int64
Shops_2           object
Price            float64
dtype: object

## 8. Выведите статистику для числовых признаков и для категориальных признаков.

In [25]:
data.describe()

Id    DistrictId         Rooms        Square   LifeSquare  \
count  10000.00000  10000.000000  10000.000000  10000.000000  7887.000000   
mean    8383.40770     50.400800      1.890500     56.315775    37.199645   
std     4859.01902     43.587592      0.839512     21.058732    86.241209   
min        0.00000      0.000000      0.000000      1.136859     0.370619   
25%     4169.50000     20.000000      1.000000     41.774881    22.769832   
50%     8394.50000     36.000000      2.000000     52.513310    32.781260   
75%    12592.50000     75.000000      2.000000     65.900625    45.128803   
max    16798.00000    209.000000     19.000000    641.065193  7480.592129   

       KitchenSquare         Floor    HouseFloor     HouseYear     Ecology_1  \
count   10000.000000  10000.000000  10000.000000  1.000000e+04  10000.000000   
mean        6.273300      8.526700     12.609400  3.990166e+03      0.118858   
std        28.560917      5.241148      6.775974  2.005003e+05      0.119025   
min         0.000000      1.000000      0.000000  1.910000e+03      0.000000   
25%         1.000000      4.000000      9.000000  1.974000e+03      0.017647   
50%         6.000000      7.000000     13.000000  1.977000e+03      0.075424   
75%         9.000000     12.000000     17.000000  2.001000e+03      0.195781   
max      2014.000000     42.000000    117.000000  2.005201e+07      0.521867   

           Social_1      Social_2      Social_3  Healthcare_1   Helthcare_2  \
count  10000.000000  10000.000000  10000.000000   5202.000000  10000.000000   
mean      24.687000   5352.157400      8.039200   1142.904460      1.319500   
std       17.532614   4006.799803     23.831875   1021.517264      1.493601   
min        0.000000    168.000000      0.000000      0.000000      0.000000   
25%        6.000000   1564.000000      0.000000    350.000000      0.000000   
50%       25.000000   5285.000000      2.000000    900.000000      1.000000   
75%       36.000000   7227.000000      5.000000   1548.000000      2.000000   
max       74.000000  19083.000000    141.000000   4849.000000      6.000000   

            Shops_1          Price  
count  10000.000000   10000.000000  
mean       4.231300  214138.857399  
std        4.806341   92872.293865  
min        0.000000   59174.778028  
25%        1.000000  153872.633942  
50%        3.000000  192269.644879  
75%        6.000000  249135.462171  
max       23.000000  633233.466570

In [26]:
data.describe(include=object)

Ecology_2 Ecology_3 Shops_2
count      10000     10000   10000
unique         2         2       2
top            B         B       B
freq        9903      9725    9175

## 9. Удалите из таблицы столбцы, содержащие идентификаторы.

In [27]:
data = data.drop(['Id', 'DistrictId'], axis = 1)
data.head()

Rooms      Square  LifeSquare  KitchenSquare  Floor  HouseFloor  HouseYear  \
0    3.0  115.027311         NaN           10.0      4        10.0       2014   
1    1.0   39.832524   23.169223            8.0      7         8.0       1966   
2    3.0   78.342215   47.671972           10.0      2        17.0       1988   
3    1.0   40.409907         NaN            1.0     10        22.0       1977   
4    2.0   64.285067   38.562517            9.0     16        16.0       1972   

   Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  Social_3  Healthcare_1  \
0   0.075424         B         B        11      3097         0           NaN   
1   0.118537         B         B        30      6207         1        1183.0   
2   0.025609         B         B        33      5261         0         240.0   
3   0.007122         B         B         1       264         0           NaN   
4   0.282798         B         B        33      8667         2           NaN   

   Helthcare_2  Shops_1 Shops_2          Price  
0            0        0       B  305018.871089  
1            1        0       B  177734.553407  
2            3        1       B  282078.720850  
3            0        1       B  168106.007630  
4            0        6       B  343995.102962

## 10. Выведите названия колонок. Переименуйте названия колонок на русский язык.

In [28]:
dict_rus = {'Rooms':'Комнаты', 'Square':'Площадь', 'LifeSquare':'Жилая площадь', 'KitchenSquare':'Площадь кухни', 'Floor':'Этаж', 'HouseFloor':'Этажей в доме', 'HouseYear':'Год постройки', 'Ecology_1':'Экология_1', 'Ecology_2':'Экология_2', 'Ecology_3':'Экология_3', 'Social_1':'Социал_1', 'Social_2':'Социал_2', 'Social_3':'Социал_3', 'Healthcare_1':'Здравоохранение_1', 'Helthcare_2':'Здравоохранение_2', 'Shops_1':'Магазины_1', 'Shops_2':'Магазины_2', 'Price':'Цена'}


In [29]:
data.columns

Index(['Rooms', 'Square', 'LifeSquare', 'KitchenSquare', 'Floor', 'HouseFloor',
       'HouseYear', 'Ecology_1', 'Ecology_2', 'Ecology_3', 'Social_1',
       'Social_2', 'Social_3', 'Healthcare_1', 'Helthcare_2', 'Shops_1',
       'Shops_2', 'Price'],
      dtype='object')

In [30]:
data = data.rename(columns = dict_rus)
data

Комнаты     Площадь  Жилая площадь  Площадь кухни  Этаж  Этажей в доме  \
0         3.0  115.027311            NaN           10.0     4           10.0   
1         1.0   39.832524      23.169223            8.0     7            8.0   
2         3.0   78.342215      47.671972           10.0     2           17.0   
3         1.0   40.409907            NaN            1.0    10           22.0   
4         2.0   64.285067      38.562517            9.0    16           16.0   
...       ...         ...            ...            ...   ...            ...   
9995      2.0   49.090728      33.272626            6.0     3           12.0   
9996      2.0   64.307684      37.038420            9.0    13            0.0   
9997      1.0   29.648057      16.555363            5.0     3            5.0   
9998      1.0   32.330292      22.326870            5.0     3            9.0   
9999      1.0   35.815476      22.301367            6.0     9            9.0   

      Год постройки  Экология_1 Экология_2 Экология_3  Социал_1  Социал_2  \
0              2014    0.075424          B          B        11      3097   
1              1966    0.118537          B          B        30      6207   
2              1988    0.025609          B          B        33      5261   
3              1977    0.007122          B          B         1       264   
4              1972    0.282798          B          B        33      8667   
...             ...         ...        ...        ...       ...       ...   
9995           1981    0.300323          B          B        52     10311   
9996           1977    0.072158          B          B         2       629   
9997           1958    0.460556          B          B        20      4386   
9998           1969    0.194489          B          B        47      8004   
9999           1975    0.127376          B          B        43      8429   

      Социал_3  Здравоохранение_1  Здравоохранение_2  Магазины_1 Магазины_2  \
0            0                NaN                  0           0          B   
1            1             1183.0                  1           0          B   
2            0              240.0                  3           1          B   
3            0                NaN                  0           1          B   
4            2                NaN                  0           6          B   
...        ...                ...                ...         ...        ...   
9995         6                NaN                  1           9          B   
9996         1                NaN                  0           0          A   
9997        14                NaN                  1           5          B   
9998         3              125.0                  3           5          B   
9999         3                NaN                  3           9          B   

               Цена  
0     305018.871089  
1     177734.553407  
2     282078.720850  
3     168106.007630  
4     343995.102962  
...             ...  
9995  119367.455796  
9996  199715.148807  
9997  165953.912580  
9998  171842.411855  
9999  177685.627486  

[10000 rows x 18 columns]

## 11. Выведите отдельно столбец, содержащий цену, по его номеру столбца и по названию в виде серии и в виде датафрейма. Выведите первую, десятую и предпоследнюю строку таблицы.

In [31]:
data[['Цена']]

Цена
0     305018.871089
1     177734.553407
2     282078.720850
3     168106.007630
4     343995.102962
...             ...
9995  119367.455796
9996  199715.148807
9997  165953.912580
9998  171842.411855
9999  177685.627486

[10000 rows x 1 columns]

In [32]:
type(data[['Цена']])

pandas.core.frame.DataFrame

In [33]:
data['Цена']

0       305018.871089
1       177734.553407
2       282078.720850
3       168106.007630
4       343995.102962
            ...      
9995    119367.455796
9996    199715.148807
9997    165953.912580
9998    171842.411855
9999    177685.627486
Name: Цена, Length: 10000, dtype: float64

In [34]:
data.iloc[:, -1]

0       305018.871089
1       177734.553407
2       282078.720850
3       168106.007630
4       343995.102962
            ...      
9995    119367.455796
9996    199715.148807
9997    165953.912580
9998    171842.411855
9999    177685.627486
Name: Цена, Length: 10000, dtype: float64

In [35]:
data.iloc[:, -1:]

Цена
0     305018.871089
1     177734.553407
2     282078.720850
3     168106.007630
4     343995.102962
...             ...
9995  119367.455796
9996  199715.148807
9997  165953.912580
9998  171842.411855
9999  177685.627486

[10000 rows x 1 columns]

In [36]:
data.iloc[[0, 9, -2]]

Комнаты     Площадь  Жилая площадь  Площадь кухни  Этаж  Этажей в доме  \
0         3.0  115.027311            NaN           10.0     4           10.0   
9         3.0   79.867477      75.085125            1.0     3           17.0   
9998      1.0   32.330292      22.326870            5.0     3            9.0   

      Год постройки  Экология_1 Экология_2 Экология_3  Социал_1  Социал_2  \
0              2014    0.075424          B          B        11      3097   
9              2014    0.243205          B          B         5      1564   
9998           1969    0.194489          B          B        47      8004   

      Социал_3  Здравоохранение_1  Здравоохранение_2  Магазины_1 Магазины_2  \
0            0                NaN                  0           0          B   
9            0              540.0                  0           0          B   
9998         3              125.0                  3           5          B   

               Цена  
0     305018.871089  
9     194756.023945  
9998  171842.411855

In [37]:
data.iloc[[8]]

Комнаты    Площадь  Жилая площадь  Площадь кухни  Этаж  Этажей в доме  \
8      1.0  46.887892      44.628132            1.0    12           20.0   

   Год постройки  Экология_1 Экология_2 Экология_3  Социал_1  Социал_2  \
8           1977    0.007122          B          B         1       264   

   Социал_3  Здравоохранение_1  Здравоохранение_2  Магазины_1 Магазины_2  \
8         0                NaN                  0           1          B   

            Цена  
8  160400.401732

## 12. Выведите два столбца "Площадь" и "Цена" только для трёхкомнатных квартир.

In [40]:
df = data[data['Комнаты']== 3][['Площадь','Цена']]
df

Площадь           Цена
0     115.027311  305018.871089
2      78.342215  282078.720850
5      62.528465  161044.944138
9      79.867477  194756.023945
10     74.199049  512797.373401
...          ...            ...
9971  105.649530  500562.663412
9973   81.103039  260456.004692
9976   98.201000  210437.316223
9977   76.412253  381850.701985
9993   84.486078  264213.558631

[2235 rows x 2 columns]

## 13. Сохраните получившуюся таблицу в файлы формата csv и xlsx. Прочитайте их и убедитесь, что данные отображаются корректно.

In [44]:
df.to_csv('df.csv')


In [46]:
df_csv=pd.read_csv('df.csv')
df_csv

Площадь           Цена
0     115.027311  305018.871089
1      78.342215  282078.720850
2      62.528465  161044.944138
3      79.867477  194756.023945
4      74.199049  512797.373401
...          ...            ...
2230  105.649530  500562.663412
2231   81.103039  260456.004692
2232   98.201000  210437.316223
2233   76.412253  381850.701985
2234   84.486078  264213.558631

[2235 rows x 2 columns]

In [48]:
df.to_excel('df.xlsx')

In [50]:
df_excel=pd.read_excel('df.xlsx', index_col='Unnamed: 0')
df_excel

Площадь           Цена
0     115.027311  305018.871089
2      78.342215  282078.720850
5      62.528465  161044.944138
9      79.867477  194756.023945
10     74.199049  512797.373401
...          ...            ...
9971  105.649530  500562.663412
9973   81.103039  260456.004692
9976   98.201000  210437.316223
9977   76.412253  381850.701985
9993   84.486078  264213.558631

[2235 rows x 2 columns]

## 14. Выделите в отдельную таблицу (DataFrame) последние десять строк. Удалите в ней столбец с ценой. Склейте ее с первоначальной таблицей при помощи concat. Заполните отсутствующие значения цены средним по таблице.

## 15. Теперь выделите пять последних колонок в отдельную таблицу. Удалите в ней строки, в которых цена ниже среднего. Присоедините эту таблицу к исходной.

## 16. Используя изначальную версию датасета считайте в ноутбук первые 400 строк.

## 17. Постройте круговую диаграмму для признака Rooms, иллюстрирующую количество квартир в процентах в зависимости от количества комнат. Сделайте сектор с наибольшим числом квартир выдвинутым.

## 18. Постройте гистограмму по целевой переменной Price. Оцените визуально, по какой цене продаётся наибольшее количество квартир.

## 19. Постройте диаграммы рассеяния для признаков Rooms, Square, HouseFloor, HouseYear в зависимости от целевой переменной Price в одной области figure. Оцените визуально, есть ли среди них такие, на которых разброс точек близок к линейной функции.

## 20. Постройте ядерную оценку плотности целевой переменной Price. Оцените визуально, напоминает ли полученный график нормальное распределение. Постройте двумерную ядерную оценку плотности для целевой переменной Price и признака HouseFloor, затем оцените визуально на каких этажах и по какой цене продаётся основная масса квартир.

## 21. Постройте ящиковую диаграмму признака Square. Оцените визуально имеются ли выбросы, и, если да, то начиная с какого размера площади значение признака можно считать выбросом.

## 22. При помощи сетки графиков PairGrid визуализируйте попарные отношения признаков Rooms, Square, HouseFloor, HouseYear, Price следующим образом: на диагонали - гистограммы, под диагональю - ядерные оценки плотности, над диагональю - диаграммы рассеяния. По результатам визуализации сделайте выводы.

## 23. Постройте тепловую карту матрицы корреляции (df.corr()) признаков Rooms, Square, HouseFloor, HouseYear, Price. По ней определите, какие признаки являются зависимыми (у таких признаков коэффициент корреляции близок к единице).